apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{.Release.Name}}-vote-back-hpa
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 3  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Release.Name}}-vote-back
  targetCPUUtilizationPercentage: 50 # target CPU utilization

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{.Release.Name}}-vote-front-hpa
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 3  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Release.Name}}-vote-front
  targetCPUUtilizationPercentage: 50 # target CPU utilization